.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. nestcoin_qt test_nestcoin_qt
clean: FORCE
	$(MAKE) -C .. nestcoin_qt_clean test_nestcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_nestcoin_qt_check
nestcoin-qt nestcoin-qt.exe: FORCE
	 $(MAKE) -C .. nestcoin_qt
